-- Bronze table for samples.tpch.orders (overwrite mode).
-- Generated by scripts/new_bronze_migration.py from the source table's schema: source columns keep their
-- names and types, and the _ columns are ingestion metadata. Review before committing.
CREATE TABLE IF NOT EXISTS `${catalog}`.`${bronze_schema}`.tpch_orders (
  o_orderkey BIGINT,
  o_custkey BIGINT,
  o_orderstatus STRING,
  o_totalprice DECIMAL(18,2),
  o_orderdate DATE,
  o_orderpriority STRING,
  o_clerk STRING,
  o_shippriority INT,
  o_comment STRING,
  _batch_id STRING,
  _ingested_at TIMESTAMP,
  _source_table STRING,
  _source_file STRING
)
COMMENT 'Raw samples.tpch.orders, loaded in overwrite mode, one _batch_id per load';
