-- Bronze table for samples.nyctaxi.trips (append mode).
-- Generated by scripts/new_bronze_migration.py from the source table's schema: source columns keep their
-- names and types, and the _ columns are ingestion metadata. Review before committing.
CREATE TABLE IF NOT EXISTS `${catalog}`.`${bronze_schema}`.trips (
  tpep_pickup_datetime TIMESTAMP,
  tpep_dropoff_datetime TIMESTAMP,
  trip_distance DOUBLE,
  fare_amount DOUBLE,
  pickup_zip INT,
  dropoff_zip INT,
  _batch_id STRING,
  _ingested_at TIMESTAMP,
  _source_table STRING,
  _source_file STRING
)
COMMENT 'Raw samples.nyctaxi.trips, loaded in append mode, one _batch_id per load';
