-- Bronze table for samples.tpch.partsupp (overwrite mode).
-- Generated by scripts/new_bronze_migration.py from the source table's schema: source columns keep their
-- names and types, and the _ columns are ingestion metadata. Review before committing.
CREATE TABLE IF NOT EXISTS `${catalog}`.`${bronze_schema}`.tpch_partsupp (
  ps_partkey BIGINT,
  ps_suppkey BIGINT,
  ps_availqty INT,
  ps_supplycost DECIMAL(18,2),
  ps_comment STRING,
  _batch_id STRING,
  _ingested_at TIMESTAMP,
  _source_table STRING,
  _source_file STRING
)
COMMENT 'Raw samples.tpch.partsupp, loaded in overwrite mode, one _batch_id per load';
