-- Bronze table for samples.tpch.nation (overwrite mode).
-- Generated by scripts/new_bronze_migration.py from the source table's schema: source columns keep their
-- names and types, and the _ columns are ingestion metadata. Review before committing.
CREATE TABLE IF NOT EXISTS `${catalog}`.`${bronze_schema}`.tpch_nation (
  n_nationkey BIGINT,
  n_name STRING,
  n_regionkey BIGINT,
  n_comment STRING,
  _batch_id STRING,
  _ingested_at TIMESTAMP,
  _source_table STRING,
  _source_file STRING
)
COMMENT 'Raw samples.tpch.nation, loaded in overwrite mode, one _batch_id per load';
