-- Bronze table for samples.tpch.supplier (overwrite mode).
-- Generated by scripts/new_bronze_migration.py from the source table's schema: source columns keep their
-- names and types, and the _ columns are ingestion metadata. Review before committing.
CREATE TABLE IF NOT EXISTS `${catalog}`.`${bronze_schema}`.tpch_supplier (
  s_suppkey BIGINT,
  s_name STRING,
  s_address STRING,
  s_nationkey BIGINT,
  s_phone STRING,
  s_acctbal DECIMAL(18,2),
  s_comment STRING,
  _batch_id STRING,
  _ingested_at TIMESTAMP,
  _source_table STRING,
  _source_file STRING
)
COMMENT 'Raw samples.tpch.supplier, loaded in overwrite mode, one _batch_id per load';
